# Generated by Django 2.2.7 on 2019-11-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
