# Generated by Django 2.2.7 on 2019-11-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191123_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='banner/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name_plural': 'Imagens Banner',
                'ordering': ['imagem'],
                'verbose_name': 'Imagem Banner',
            },
        ),
    ]
