# Generated by Django 2.2.7 on 2019-11-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191128_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParceirosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Parceiro')),
                ('logo', models.ImageField(upload_to='parceiros/', verbose_name='Logo')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name_plural': 'Parceiros',
                'verbose_name': 'Parceiro',
            },
        ),
    ]
